In [1]:
import numpy as np
s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]

old = np.array([
    ['62', '71', '55', '80'],
    ['49', '58', '66', '73']
])

# Task 1: Build one table from s1, s2 and s3
marks = np.array([s1, s2, s3])
print(marks)

# Task 2: Print number of students and number of subjects
students, subjects = marks.shape
print("Number of students:", students)
print("Number of subjects:", subjects)

# Task 3: Print total count of marks entries stored in the table
print("Total marks entries:", marks.size)

# Task 4: Store the same table as decimals
marks_decimal = marks.astype(float)
print(marks_decimal)

# Task 5: Convert old into a form where arithmetic works
old_numeric = old.astype(int)
print(old_numeric.sum(axis=1))

# Task 6: Attach old below the main table
final_table = np.vstack((marks, old_numeric))
print(final_table)

[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
Number of students: 3
Number of subjects: 4
Total marks entries: 12
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
[268 246]
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]


In [2]:
import numpy as np

# Task 1: Blank mark sheet for 6 students and 4 subjects
blank_marks = np.zeros((6, 4))
print(blank_marks)

# Task 2: Same size table where every student is temporarily given 35
marks_35 = np.full((6, 4), 35)
print(marks_35)

# Task 3: Batch has roll numbers from 101 to 130
roll_numbers = np.arange(101, 131, 2)
print(roll_numbers)
print(len(roll_numbers))

# Task 4: Split a 3-hour practical into 7 equally spaced time markers
time_markers = np.linspace(0, 3, 7)
print(time_markers)

# Task 5: 5 x 5 table with 10 on diagonal and 0 elsewhere
table_5 = np.eye(5) * 10
print(table_5)

# Task 6: 4 x 4 table with 100 on diagonal and 35 elsewhere
table_4 = np.full((4, 4), 35)
np.fill_diagonal(table_4, 100)
print(table_4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
15
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]


In [3]:
import numpy as np
present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])

# Task 1: Print first and last student's attendance
print(present[[0, -1]])

# Task 2: Attendance of every alternate student, starting from second
print(present[1::2])

# Task 3: Print the last four values
print(present[-4:])

# Task 4: Reverse the row, then print every third value
reversed_present = present[::-1]
print(reversed_present[::3])

# Task 5: Change attendance of two middle students to 30 each
present[4:6] = 30
print(present)

# Task 6: Compare first half with second half position by position
difference = present[:5] - present[5:]
print(difference)

# Task 7: Print the three values of the row after reversing it
print(present[::-1][:3])

[22 23]
[18 12 24 21 23]
[ 9 21 17 23]
[23  9 12 22]
[22 18 25 12 30 30  9 21 17 23]
[-8  9  4 -5  7]
[23 17 21]


In [4]:
import numpy as np

# Columns:
# Math, Physics, Chemistry, English
marks = np.array([
    [72, 85, 60, 91],
    [45, 30, 98, 55],
    [88, 66, 74, 100],
    [95, 92, 55, 40],
    [30, 48, 62, 70]
])

# Task 1: Print Physics and Chemistry marks
# of the middle three students only
print(marks[1:4, 1:3])

# Task 2: Print the last subject's marks for the whole class
print(marks[:, -1])

# Task 3: Table containing only the first
# and last subject of every student
print(marks[:, [0, -1]])

# Task 4: Print the mark sheet with students in reverse order
print(marks[::-1])

# Task 5: Increase only Chemistry marks by 5
marks[:, 2] += 5
print(marks)

# Task 6: Print the mark in the last row
# and second-last column
print(marks[-1, -2])

# Task 7: Table of the last two students
# and their first two subjects
print(marks[-2:, :2])

[[30 98]
 [66 74]
 [92 55]]
[ 91  55 100  40  70]
[[ 72  91]
 [ 45  55]
 [ 88 100]
 [ 95  40]
 [ 30  70]]
[[ 30  48  62  70]
 [ 95  92  55  40]
 [ 88  66  74 100]
 [ 45  30  98  55]
 [ 72  85  60  91]]
[[ 72  85  65  91]
 [ 45  30 103  55]
 [ 88  66  79 100]
 [ 95  92  60  40]
 [ 30  48  67  70]]
67
[[95 92]
 [30 48]]
