In [3]:
import numpy as np
s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]

old = np.array([
    ['62', '71', '55', '80'],
    ['49', '58', '66', '73']
])

# Task 1:
marks = np.array([s1, s2, s3])
print(marks)

# Task 2:
students, subjects = marks.shape
print("Number of students:", students)
print("Number of subjects:", subjects)

# Task 3:
print("Total marks entries:", marks.size)

# Task 4:
marks_decimal = marks.astype(float)
print(marks_decimal)

# Task 5:
old_numeric = old.astype(int)
print(old_numeric.sum(axis=1))

# Task 6:
final_table = np.vstack((marks, old_numeric))
print(final_table)

[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
Number of students: 3
Number of subjects: 4
Total marks entries: 12
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
[268 246]
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]


In [4]:
import numpy as np

# Task 1:
blank_marks = np.zeros((6, 4))
print(blank_marks)

# Task 2: 
marks_35 = np.full((6, 4), 35)
print(marks_35)

# Task 3:
roll_numbers = np.arange(101, 131, 2)
print(roll_numbers)
print(len(roll_numbers))

# Task 4:
time_markers = np.linspace(0, 3, 7)
print(time_markers)

# Task 5:
table_5 = np.eye(5) * 10
print(table_5)

# Task 6:
table_4 = np.full((4, 4), 35)
np.fill_diagonal(table_4, 100)
print(table_4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
15
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]


In [6]:
import numpy as np
present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])

# Task 1: 
print(present[[0, -1]])

# Task 2:
print(present[1::2])

# Task 3: 
print(present[-4:])

# Task 4:
reversed_present = present[::-1]
print(reversed_present[::3])

# Task 5: 
present[4:6] = 30
print(present)

# Task 6: 
difference = present[:5] - present[5:]
print(difference)

# Task 7: 
print(present[::-1][:3])

[22 23]
[18 12 24 21 23]
[ 9 21 17 23]
[23  9 12 22]
[22 18 25 12 30 30  9 21 17 23]
[-8  9  4 -5  7]
[23 17 21]


In [7]:
import numpy as np

# Columns:
# Math, Physics, Chemistry, English
marks = np.array([
    [72, 85, 60, 91],
    [45, 30, 98, 55],
    [88, 66, 74, 100],
    [95, 92, 55, 40],
    [30, 48, 62, 70]
])

# Task 1: 
print(marks[1:4, 1:3])

# Task 2: 
print(marks[:, -1])

# Task 3: 
print(marks[:, [0, -1]])

# Task 4:
print(marks[::-1])

# Task 5: 
marks[:, 2] += 5
print(marks)

# Task 6: 
print(marks[-1, -2])

# Task 7: 
print(marks[-2:, :2])

[[30 98]
 [66 74]
 [92 55]]
[ 91  55 100  40  70]
[[ 72  91]
 [ 45  55]
 [ 88 100]
 [ 95  40]
 [ 30  70]]
[[ 30  48  62  70]
 [ 95  92  55  40]
 [ 88  66  74 100]
 [ 45  30  98  55]
 [ 72  85  60  91]]
[[ 72  85  65  91]
 [ 45  30 103  55]
 [ 88  66  79 100]
 [ 95  92  60  40]
 [ 30  48  67  70]]
67
[[95 92]
 [30 48]]


In [8]:
import numpy as np
totals = np.array([245, 310, 178, 392, 140, 265, 199, 155, 288, 132])

# 1.
above_250 = totals[totals > 250]
print(above_250)

# 2. 
between_180_250 = totals[(totals > 180) & (totals < 250)]
print(between_180_250)

# 3. 
below_150_or_above_380 = totals[(totals < 150) | (totals > 380)]
print(below_150_or_above_380)

# 4.
count = np.sum((totals > 180) & (totals < 250))
print(count)

# 5.
average = np.mean(totals[totals > 200])
print(average)

# 6. 
indices = np.where(totals < 150)[0]
print(indices)

# 7. 
highest_non_merit = np.max(totals[totals <= 250])
print(highest_non_merit)

[310 392 265 288]
[245 199]
[392 140 132]
2
300.0
[4 9]
245


In [9]:
import numpy as np

marks = np.array([40, 55, 62, 88, 95, 33, 71, 58])

# 1. 
increased_marks = np.round(marks * 1.15, 2)
print(increased_marks)

# 2. 
corrected_marks = np.minimum(increased_marks, 100)
print(corrected_marks)

# 3. 
gain = corrected_marks - marks
count_less_than_10 = np.sum(gain < 10)
print(count_less_than_10)

# 4.
failing_before = np.sum(marks < 40)


failing_after = np.sum(corrected_marks < 40)

print(failing_before)
print(failing_after)

# 5. 
topper_marks = np.max(corrected_marks)
percentage = np.round((corrected_marks / topper_marks) * 100, 1)
print(percentage)

# 6. 
total_marks_given = np.sum(corrected_marks - marks)
print(total_marks_given)

[ 46.    63.25  71.3  101.2  109.25  37.95  81.65  66.7 ]
[ 46.    63.25  71.3  100.   100.    37.95  81.65  66.7 ]
6
1
1
[ 46.   63.2  71.3 100.  100.   38.   81.6  66.7]
64.85000000000001


In [ ]:
import numpy as np
marks = np.array([72, 45, 88, 95, 30, 67, 91, 54, 78, 39])

# 1. 
average = np.mean(marks)
median = np.median(marks)

print("Average:", average)
print("Median:", median)


# 2. 
gap = np.max(marks) - np.min(marks)
print("Gap:", gap)


# 3.
topper_index = np.argmax(marks)
weakest_index = np.argmin(marks)

print("Topper index:", topper_index)
print("Weakest index:", weakest_index)


# 4. 
sorted_marks = np.sort(marks)
second_highest = sorted_marks[-2]
print("Second highest:", second_highest)


# 5. 
above_average = np.sum(marks > average)
print("Above average:", above_average)


# 6.
below_median = np.sum(marks < median)
print("Below median:", below_median)


# 7.
marks_without_topper = np.delete(marks, topper_index)
new_average = np.mean(marks_without_topper)

print("Average after removing topper:", round(new_average, 2))

Average: 65.9
Median: 69.5
Gap: 65
Topper index: 3
Weakest index: 4
Second highest: 91
Above average: 6
Below median: 5
Average after removing topper: 62.67


In [11]:
import numpy as np

marks = np.array([
    [72, 85, 60, 91],
    [45, 30, 98, 55],
    [88, 66, 74, 100],
    [95, 92, 55, 40],
    [30, 48, 62, 78]
])


# 1. 
subject_average = np.mean(marks, axis=0)

print("Subject averages:", subject_average)

student_total = np.sum(marks, axis=1)

print("Student totals:", student_total)


# 2.
toughest_subject = np.argmin(subject_average)

print("Toughest subject index:", toughest_subject)


# 3. 
top_student = np.argmax(student_total)

print("Top student index:", top_student)


# 4.
top_marks_each_subject = np.max(marks, axis=0)

print("Top marks in each subject:", top_marks_each_subject)


# 5.
students_above_60 = np.sum(marks > 60, axis=0)

print("Students above 60:", students_above_60)


# 6.
subject_range = np.max(marks, axis=0) - np.min(marks, axis=0)

most_spread_subject = np.argmax(subject_range)

print("Most spread out subject index:", most_spread_subject)


# 7. 
chemistry_marks = marks[:, 2]

lowest_chemistry_student = np.argmin(chemistry_marks)

total_of_lowest_chemistry_student = student_total[lowest_chemistry_student]

print("Total marks:", total_of_lowest_chemistry_student)

Subject averages: [66.  64.2 69.8 72.8]
Student totals: [308 228 328 282 218]
Toughest subject index: 1
Top student index: 2
Top marks in each subject: [ 95  92  98 100]
Students above 60: [3 3 3 3]
Most spread out subject index: 0
Total marks: 282


In [12]:
import numpy as np

participants = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

np.random.seed(42)

winners = np.random.choice(participants, 3, replace=False)
print(winners)

attendance = np.random.randint(60, 101, 10)
print(attendance)

random_table = np.random.randint(0, 101, (4, 3))
print(random_table)

shuffled = np.random.permutation(participants)
print(shuffled[:4])

rolls = np.random.randint(1, 7, 20)
print(np.sum(rolls == 6))

crossed_80 = participants[attendance > 80]
print(crossed_80)

[109 102 106]
[78 82 70 70 83 95 99 83 62 81]
[[52  1 87]
 [29 37  1]
 [63 59 20]
 [32 75 57]]
[108 105 110 104]
3
[102 105 106 107 108 110]


In [13]:
import numpy as np

positions = np.array([0, 5, 12, 20, 30])

distances = np.abs(positions[:, None] - positions[None, :])
distances = distances.astype(float)
np.fill_diagonal(distances, np.inf)

print(distances)

farthest_distance = np.max(distances, axis=1)
print(farthest_distance)

nearest_to_zero = np.argmin(distances[0, 1:]) + 1
print(nearest_to_zero)

upper = distances.copy()
np.fill_diagonal(upper, np.inf)
upper[np.tril_indices(5)] = np.inf
closest_pair = np.unravel_index(np.argmin(upper), upper.shape)
print(closest_pair)

roll_numbers = np.arange(1, 25).reshape(-1, 6)
print(roll_numbers)

[[inf  5. 12. 20. 30.]
 [ 5. inf  7. 15. 25.]
 [12.  7. inf  8. 18.]
 [20. 15.  8. inf 10.]
 [30. 25. 18. 10. inf]]
[inf inf inf inf inf]
1
(np.int64(0), np.int64(1))
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
