In [1]:
import numpy as np
s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]

old = np.array([
    ['62', '71', '55', '80'],
    ['49', '58', '66', '73']
])

# Task 1: Build one table from s1, s2 and s3
marks = np.array([s1, s2, s3])
print(marks)

# Task 2: Print number of students and number of subjects
students, subjects = marks.shape
print("Number of students:", students)
print("Number of subjects:", subjects)

# Task 3: Print total count of marks entries stored in the table
print("Total marks entries:", marks.size)

# Task 4: Store the same table as decimals
marks_decimal = marks.astype(float)
print(marks_decimal)

# Task 5: Convert old into a form where arithmetic works
old_numeric = old.astype(int)
print(old_numeric.sum(axis=1))

# Task 6: Attach old below the main table
final_table = np.vstack((marks, old_numeric))
print(final_table)

[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
Number of students: 3
Number of subjects: 4
Total marks entries: 12
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
[268 246]
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]


In [2]:
import numpy as np

# Task 1: Blank mark sheet for 6 students and 4 subjects
blank_marks = np.zeros((6, 4))
print(blank_marks)

# Task 2: Same size table where every student is temporarily given 35
marks_35 = np.full((6, 4), 35)
print(marks_35)

# Task 3: Batch has roll numbers from 101 to 130
roll_numbers = np.arange(101, 131, 2)
print(roll_numbers)
print(len(roll_numbers))

# Task 4: Split a 3-hour practical into 7 equally spaced time markers
time_markers = np.linspace(0, 3, 7)
print(time_markers)

# Task 5: 5 x 5 table with 10 on diagonal and 0 elsewhere
table_5 = np.eye(5) * 10
print(table_5)

# Task 6: 4 x 4 table with 100 on diagonal and 35 elsewhere
table_4 = np.full((4, 4), 35)
np.fill_diagonal(table_4, 100)
print(table_4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
15
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]


In [3]:
import numpy as np
present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])

# Task 1: Print first and last student's attendance
print(present[[0, -1]])

# Task 2: Attendance of every alternate student, starting from second
print(present[1::2])

# Task 3: Print the last four values
print(present[-4:])

# Task 4: Reverse the row, then print every third value
reversed_present = present[::-1]
print(reversed_present[::3])

# Task 5: Change attendance of two middle students to 30 each
present[4:6] = 30
print(present)

# Task 6: Compare first half with second half position by position
difference = present[:5] - present[5:]
print(difference)

# Task 7: Print the three values of the row after reversing it
print(present[::-1][:3])

[22 23]
[18 12 24 21 23]
[ 9 21 17 23]
[23  9 12 22]
[22 18 25 12 30 30  9 21 17 23]
[-8  9  4 -5  7]
[23 17 21]


In [4]:
import numpy as np

# Columns:
# Math, Physics, Chemistry, English
marks = np.array([
    [72, 85, 60, 91],
    [45, 30, 98, 55],
    [88, 66, 74, 100],
    [95, 92, 55, 40],
    [30, 48, 62, 70]
])

# Task 1: Print Physics and Chemistry marks
# of the middle three students only
print(marks[1:4, 1:3])

# Task 2: Print the last subject's marks for the whole class
print(marks[:, -1])

# Task 3: Table containing only the first
# and last subject of every student
print(marks[:, [0, -1]])

# Task 4: Print the mark sheet with students in reverse order
print(marks[::-1])

# Task 5: Increase only Chemistry marks by 5
marks[:, 2] += 5
print(marks)

# Task 6: Print the mark in the last row
# and second-last column
print(marks[-1, -2])

# Task 7: Table of the last two students
# and their first two subjects
print(marks[-2:, :2])

[[30 98]
 [66 74]
 [92 55]]
[ 91  55 100  40  70]
[[ 72  91]
 [ 45  55]
 [ 88 100]
 [ 95  40]
 [ 30  70]]
[[ 30  48  62  70]
 [ 95  92  55  40]
 [ 88  66  74 100]
 [ 45  30  98  55]
 [ 72  85  60  91]]
[[ 72  85  65  91]
 [ 45  30 103  55]
 [ 88  66  79 100]
 [ 95  92  60  40]
 [ 30  48  67  70]]
67
[[95 92]
 [30 48]]


In [1]:
import numpy as np
totals = np.array([245, 310, 178, 392, 140, 265, 199, 155, 288, 132])

# 1. Students who scored above 250
above_250 = totals[totals > 250]
print(above_250)

# 2. Students who scored above 180 but below 250
between_180_250 = totals[(totals > 180) & (totals < 250)]
print(between_180_250)

# 3. Students who scored either below 150 or above 380
below_150_or_above_380 = totals[(totals < 150) | (totals > 380)]
print(below_150_or_above_380)

# 4. Number of students in the band of task 2
count = np.sum((totals > 180) & (totals < 250))
print(count)

# 5. Average of students who scored above 200
average = np.mean(totals[totals > 200])
print(average)

# 6. Index position of every student below 150
indices = np.where(totals < 150)[0]
print(indices)

# 7. Highest total among students who did not make the merit band of task 1
# Merit band = above 250
highest_non_merit = np.max(totals[totals <= 250])
print(highest_non_merit)

[310 392 265 288]
[245 199]
[392 140 132]
2
300.0
[4 9]
245


In [2]:
import numpy as np

marks = np.array([40, 55, 62, 88, 95, 33, 71, 58])

# 1. Increase every student's marks by 15% and round to 2 decimals
increased_marks = np.round(marks * 1.15, 2)
print(increased_marks)

# 2. No student may score more than 100
corrected_marks = np.minimum(increased_marks, 100)
print(corrected_marks)

# 3. Number of students who gained less than 10 marks
gain = corrected_marks - marks
count_less_than_10 = np.sum(gain < 10)
print(count_less_than_10)

# 4. Pass mark is 40
# Number failing before increase
failing_before = np.sum(marks < 40)

# Number failing after increase
failing_after = np.sum(corrected_marks < 40)

print(failing_before)
print(failing_after)

# 5. Each student's marks as percentage of topper's marks
topper_marks = np.max(corrected_marks)
percentage = np.round((corrected_marks / topper_marks) * 100, 1)
print(percentage)

# 6. Total number of marks given away in revaluation
total_marks_given = np.sum(corrected_marks - marks)
print(total_marks_given)

[ 46.    63.25  71.3  101.2  109.25  37.95  81.65  66.7 ]
[ 46.    63.25  71.3  100.   100.    37.95  81.65  66.7 ]
6
1
1
[ 46.   63.2  71.3 100.  100.   38.   81.6  66.7]
64.85000000000001


In [3]:
import numpy as np
marks = np.array([72, 45, 88, 95, 30, 67, 91, 54, 78, 39])

# 1. Print the class average and the middle value (median)
average = np.mean(marks)
median = np.median(marks)

print("Average:", average)
print("Median:", median)


# 2. Print the gap between the highest and lowest marks
gap = np.max(marks) - np.min(marks)
print("Gap:", gap)


# 3. Print the index positions of the topper and weakest student
topper_index = np.argmax(marks)
weakest_index = np.argmin(marks)

print("Topper index:", topper_index)
print("Weakest index:", weakest_index)


# 4. Print the second highest marks in the class
sorted_marks = np.sort(marks)
second_highest = sorted_marks[-2]
print("Second highest:", second_highest)


# 5. Print how many students scored above the class average
above_average = np.sum(marks > average)
print("Above average:", above_average)


# 6. Print how many students scored below the middle value
below_median = np.sum(marks < median)
print("Below median:", below_median)


# 7. Print the class average after removing the topper
marks_without_topper = np.delete(marks, topper_index)
new_average = np.mean(marks_without_topper)

print("Average after removing topper:", round(new_average, 2))

Average: 65.9
Median: 69.5
Gap: 65
Topper index: 3
Weakest index: 4
Second highest: 91
Above average: 6
Below median: 5
Average after removing topper: 62.67


In [4]:
import numpy as np

marks = np.array([
    [72, 85, 60, 91],
    [45, 30, 98, 55],
    [88, 66, 74, 100],
    [95, 92, 55, 40],
    [30, 48, 62, 78]
])


# 1. Print the average of each subject
subject_average = np.mean(marks, axis=0)

print("Subject averages:", subject_average)


# Print the total of each student
student_total = np.sum(marks, axis=1)

print("Student totals:", student_total)


# 2. Print the index of the toughest subject for the class
# Toughest = subject with the lowest average
toughest_subject = np.argmin(subject_average)

print("Toughest subject index:", toughest_subject)


# 3. Print the index of the student who topped overall
top_student = np.argmax(student_total)

print("Top student index:", top_student)


# 4. For every subject, print the marks of the student
# who topped that subject
top_marks_each_subject = np.max(marks, axis=0)

print("Top marks in each subject:", top_marks_each_subject)


# 5. Print how many students scored above 60 in each subject
students_above_60 = np.sum(marks > 60, axis=0)

print("Students above 60:", students_above_60)


# 6. Print the index of the subject in which
# the class marks are the most spread out

subject_range = np.max(marks, axis=0) - np.min(marks, axis=0)

most_spread_subject = np.argmax(subject_range)

print("Most spread out subject index:", most_spread_subject)


# 7. Print the total marks of the student
# who scored the lowest in Chemistry

chemistry_marks = marks[:, 2]

lowest_chemistry_student = np.argmin(chemistry_marks)

total_of_lowest_chemistry_student = student_total[lowest_chemistry_student]

print("Total marks:", total_of_lowest_chemistry_student)

Subject averages: [66.  64.2 69.8 72.8]
Student totals: [308 228 328 282 218]
Toughest subject index: 1
Top student index: 2
Top marks in each subject: [ 95  92  98 100]
Students above 60: [3 3 3 3]
Most spread out subject index: 0
Total marks: 282
