In [2]:
import numpy as np

# Q1
marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

bonus = np.array([5, 2, 8])
updated_marks = marks + bonus
capped_count = np.sum(updated_marks > 100)
updated_marks = np.minimum(updated_marks, 100)

print("Q1:")
print(updated_marks)
print("Capped:", capped_count)


# Q2
matrix = np.zeros((5, 5), dtype=int)
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print("\nQ2:")
print(matrix)


# Q3
arr = np.arange(30).reshape(5, -1).T
print("\nQ3:")
print(arr)
print("Shape:", arr.shape)

try:
    invalid = np.arange(30).reshape(4, -1)
except ValueError as e:
    print("Error:", e)


# Q4
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

first = np.hstack((heights, weights))
table = np.column_stack((heights, weights))

print("\nQ4:")
print(first)
print("First shape:", first.shape)
print(table)
print("Table shape:", table.shape)


# Q5
sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])
quarters = sales.reshape(4, 3)
averages = quarters.mean(axis=1)
highest_quarter = np.argmax(averages)

print("\nQ5:")
print(quarters)
print("Quarter index:", highest_quarter)
print("Highest average:", averages[highest_quarter])


# Q6
a = np.array([2, 3, 4])
table = a.reshape(-1, 1) * a

print("\nQ6:")
print(table)


# Q7
arr = np.arange(1, 21)
arr[arr % 3 == 0] = -1

print("\nQ7:")
print(arr)

# Q9
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

medals = np.where(
    scores >= 90,
    "Gold",
    np.where(
        scores >= 75,
        "Silver",
        np.where(scores >= 60, "Bronze", "None")
    )
)

print("\nQ9:")
print(medals)
print("Gold:", np.sum(medals == "Gold"))
print("Silver:", np.sum(medals == "Silver"))
print("Bronze:", np.sum(medals == "Bronze"))
print("None:", np.sum(medals == "None"))


# Q10
m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])

rows, cols = np.where(m > 50)
new_m = m.copy()
new_m[m > 50] = 0

print("\nQ10:")
print("Rows:", rows)
print("Columns:", cols)
print("Elements:", m[rows, cols])
print(new_m)
print("Original:")
print(m)


# Q11
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

rows = np.vstack((s1, s2, s3))
columns = np.column_stack((s1, s2, s3))

print("\nQ11:")
print(rows)
print("Row shape:", rows.shape)
print(columns)
print("Column shape:", columns.shape)
print("Transpose equal:", np.array_equal(rows.T, columns))


# Q12
np.random.seed(1)
random_matrix = np.random.randint(1, 101, (6, 6))
row_max = random_matrix.max(axis=1)
col_min = random_matrix.min(axis=0)

print("\nQ12:")
print(random_matrix)
print("Row-wise maximum:", row_max)
print("Column-wise minimum:", col_min)


# Q13
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [1, 0, 2]])

result1 = A @ B.T
result2 = A.T @ B

print("\nQ13:")
print(result1)
print("Shape 1:", result1.shape)
print(result2)
print("Shape 2:", result2.shape)

# Q15
arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - arr.min()) / (arr.max() - arr.min())

print("\nQ15:")
print(normalized)


# Q16
m = np.array([[4, 8, 15],
              [16, 23, 42]])

flat = m.flatten()
ravel = m.ravel()

flat[0] = 999
ravel[0] = 888

print("\nQ16:")
print(m)
print(flat)
print(ravel)


# Q17
np.random.seed(7)
temps = np.random.randint(15, 41, 28)
weeks = temps.reshape(4, 7)
weekly_average = weeks.mean(axis=1)
hottest_week = np.argmax(weekly_average)
days_above_35 = np.sum(temps > 35)

print("\nQ17:")
print(weeks)
print("Weekly averages:", weekly_average)
print("Hottest week:", hottest_week)
print("Days above 35:", days_above_35)

# Q19
marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])

marks = np.maximum(marks, 35)
totals = marks.sum(axis=1)
topper = np.argmax(totals)

print("\nQ19:")
print(marks)
print("Topper index:", topper)
print("Topper total:", totals[topper])


# Q20
arr = np.arange(1, 11)
slice_arr = arr[2:6]
copy_arr = arr[2:6].copy()

slice_arr[0] = 999
copy_arr[0] = 999

print("\nQ20:")
print(arr)
print(slice_arr)
print(copy_arr)


# Q21
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

diagonal = np.diag(matrix)
diagonal_matrix = np.diag(np.array([1, 2, 3, 4]))

print("\nQ21:")
print(diagonal)
print(diagonal_matrix)

Q1:
[[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]
Capped: 4

Q2:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

Q3:
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]
Shape: (6, 5)
Error: cannot reshape array of size 30 into shape (4,newaxis)

Q4:
[172 158 181 166  68  52  84  59]
First shape: (8,)
[[172  68]
 [158  52]
 [181  84]
 [166  59]]
Table shape: (4, 2)

Q5:
[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]]
Quarter index: 3
Highest average: 212.66666666666666

Q6:
[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]

Q7:
[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]

Q9:
['Gold' 'Bronze' 'Silver' 'None' 'Gold' 'Silver' 'None' 'Bronze']
Gold: 2
Silver: 2
Bronze: 2
None: 2

Q10:
Rows: [0 1 1 2]
Columns: [1 0 2 0]
Elements: [80 55 99 70]
[[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]
Original:
[[10 80 45]
 [55 20 99]
 [70 33 12]]

Q11:
[[12 15 11 19 14]
 [22 18 25 21 20]
 [31 35 29 33 30