In [2]:
import numpy as np

# Q1. First 12 odd numbers using a single np.arange call
odd_numbers = np.arange(1, 24, 2)

print("Q1:")
print(odd_numbers)

# Q2. 9 equally spaced values from 5 to 45
values = np.linspace(5, 45, 9)

print("Q2:")
print(values)
print("Gap between consecutive values:", values[1] - values[0])


# Q3. Compare dtype of arange and linspace
a = np.arange(1, 10)
b = np.linspace(1, 9, 9)

print("Q3:")
print("np.arange(1, 10):", a)
print("dtype:", a.dtype)

print("np.linspace(1, 9, 9):", b)
print("dtype:", b.dtype)

print("Reason:")
print("arange gives integers here, while linspace gives floating-point values.")


# Q4. 6x6 identity matrix with integer dtype
identity_matrix = np.eye(6, dtype=int)

print("Q4:")
print(identity_matrix)


# Q5. 3x4 matrix where every element is 5
# Report shape, size and ndim
matrix = np.full((3, 4), 5)

print("Q5:")
print(matrix)

print("Shape:", matrix.shape)
print("Size:", matrix.size)
print("Ndim:", matrix.ndim)


# Q6. Check dtypes and convert b to int using astype
a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])

print("Q6:")

print("a:", a)
print("a dtype:", a.dtype)

print("b:", b)
print("b dtype:", b.dtype)

b = b.astype(int)

print("After converting b to int:")
print("b:", b)
print("b dtype:", b.dtype)

print("Do dtypes match:", a.dtype == b.dtype)



# Q7. astype(int)
arr = np.array([10.9, 25.5, 39.99])

result = arr.astype(int)

print("Q7:")
print("Original:", arr)
print("After astype(int):", result)

print("Rule: decimal part is truncated, not rounded.")


# Q8. Indexing
# arr = [10,20,30,...,100]
arr = np.arange(10, 101, 10)

print("Q8:")
print("Array:", arr)

# (a) 4th element
fourth = arr[3]

# (b) Last element using negative indexing
last = arr[-1]

# (c) 2nd-last element
second_last = arr[-2]

print("4th element:", fourth)
print("Last element:", last)
print("2nd-last element:", second_last)

# Q9. Slicing
# Extract [30 40 50 60]
print("Q9:")

part = arr[2:6]
reverse = arr[::-1]

print("30 to 60:", part)
print("Reverse:", reverse)


# Q10. Every 3rd element starting from index 1
# arr = 1 to 20
arr = np.arange(1, 21)

result = arr[1::3]

print("\nQ10:")
print("Array:", arr)
print("Every 3rd element starting from index 1:", result)


# Q11. Everything except first two and last two elements


result = arr[2:-2]

print("\nQ11:")
print("Result:", result)


# Q12. Matrix indexing and slicing
m = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

print("\nQ12:")

# (a) 3rd row
third_row = m[2, :]

# (b) Last column
last_column = m[:, -1]

# (c) Centre 3x3 block
centre = m[1:4, 1:4]

print("3rd row:")
print(third_row)

print("Last column:")
print(last_column)

print("Centre 3x3 block:")
print(centre)


# Q13. Four corner elements as 2x2 array
# Using step slicing only
corners = m[::4, ::4]

print("\nQ13:")
print(corners)


# Q14. Every alternate row AND every alternate column
# Result should be 3x3
# ============================================================

result = m[::2, ::2]

print("\nQ14:")
print(result)


# Q15. Boolean indexing
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])

print("\nQ15:")

# (a) Marks greater than 60
greater_than_60 = marks[marks > 60]

# (b) Marks between 50 and 80
between_50_80 = marks[(marks >= 50) & (marks <= 80)]

print("Marks:", marks)

print("Marks greater than 60:")
print(greater_than_60)

print("Marks between 50 and 80:")
print(between_50_80)

Q1:
[ 1  3  5  7  9 11 13 15 17 19 21 23]
Q2:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
Gap between consecutive values: 5.0
Q3:
np.arange(1, 10): [1 2 3 4 5 6 7 8 9]
dtype: int64
np.linspace(1, 9, 9): [1. 2. 3. 4. 5. 6. 7. 8. 9.]
dtype: float64
Reason:
arange gives integers here, while linspace gives floating-point values.
Q4:
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
Q5:
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape: (3, 4)
Size: 12
Ndim: 2
Q6:
a: [2 4 6]
a dtype: int64
b: [2. 4. 6.]
b dtype: float64
After converting b to int:
b: [2 4 6]
b dtype: int64
Do dtypes match: True
Q7:
Original: [10.9  25.5  39.99]
After astype(int): [10 25 39]
Rule: decimal part is truncated, not rounded.
Q8:
Array: [ 10  20  30  40  50  60  70  80  90 100]
4th element: 40
Last element: 100
2nd-last element: 90
Q9:
30 to 60: [30 40 50 60]
Reverse: [100  90  80  70  60  50  40  30  20  10]

Q10:
Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Every 3