In [1]:
x = "Hello World!"
print(x.upper())
print(x.capitalize())


HELLO WORLD!
Hello world!


In [ ]:
marks = "45, 88,72, 90,  60  "
parts = marks.split(",")

ml = []
for i in parts:
    ml.append(int(i))   

total = 0
for i in ml:
    total += i

avg = total / len(ml)

print(ml)
print(total)
print(avg)

[45, 88, 72, 90, 60]
355
71.0


In [ ]:
name = "  rahul KUMAR Sharma "
name = name.strip().title()
lst = name.split()

valid = True

for i in lst:
    if not i.isalpha():
        valid = False

if valid:
    ans = " ".join(lst)
    print(ans)
else:
    print("INVALID NAME")


Rahul Kumar Sharma


In [ ]:
d = {i: i**2 for i in range(1,11)}
print(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [ ]:
ages = np.array([92, 68, 45, 78, 30, 38, 95])
result = np.where(ages >= 75),

print(result)

((array([0, 3, 6]),), 'A')


In [8]:
A = np.array([
    [1, 2],
    [3, 4]])
B = np.array([
    [5, 6],
    [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [9]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np
S1 = ([72, 85, 60, 91])
S2 = ([45, 30 ,98 ,55])
S3 = ([88, 66, 74, 100])

table  = np.array((S1,S2,S3))
print(table)
print(table.size)
print(table.)

[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
12


In [ ]:
import numpy as np
marks = np.zeros((6, 4), dtype=int)

print("Task 1")
print(marks)
marks_35 = np.full((6, 4), 35)

print("Task 2")
print(marks_35)
roll_numbers = np.arange(101, 131, 2)

print("Task 3")
print(roll_numbers)
print()
print("Task4")
print()

Task 1
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Task 2
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
Task 3
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]



In [7]:
import numpy as np
a = np.array([10, 20, 30])
b = np.array([[10,20,30],
             [40,50,60]])
print(a)
print(b)

[10 20 30]
[[10 20 30]
 [40 50 60]]
