In [5]:
import numpy as np                # Import Numpy      

In [15]:
# Creating Array->
a = np.array([1, 2, 3, 4])            # 1-D Array 
b = np.array([[10, 20, 30, 40],       # 2-D Array
              [50, 60, 70, 80]])
print(a)
print(b)
print(type(a))                        # Checking data type 



# NumPy Silently Converts Mixed Types To One dtype -> 
c = np.array([1, 2, 3.5])                             # Turn everthing in FLOAT
d = np.array([1, 2, 3, "three"])                      # Turn everything in STRING
#e = np.array([[10, 20, 30],[40, 50, 60, 70]])        # ERROR {because rows is not equal to column(3 × 4)}
print(c)
print(d)
#print(e)

[1 2 3 4]
[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>
[1.  2.  3.5]
['1' '2' '3' 'three']


In [14]:
# Array Generators : ones,zeros,full ->
f = np.zeros((4, 3))                     # 4x3 Matrix of 0(zero) 
g = np.ones(6)                           # 1D array of 6 1s
h = np.full((3,4),5)                     # 3x3 matrix filled with 7
print(f)
print(g)
print(h)
print()

# arange vs linspace->
i = np.arange(1,20,3)                     # START, STOP EXCLUDED, STEP
j = np.linspace(0,10,5)                   # Start, Stop INCLUDED, Number of values)
k = np.eye(4)                             # Creating 4x4 matrix, 1s on the diagonal, 0s elsewhere 
l = np.array([1, 2, 3, 4], dtype=float)

print(i)
print(j)
print()
print(k)
print(l)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1. 1.]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

[ 1  4  7 10 13 16 19]
[ 0.   2.5  5.   7.5 10. ]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 2. 3. 4.]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
