In [1]:
import numpy as np                  # Import Numpy      

In [2]:
# Creating Array->
a = np.array([1, 2, 3, 4])            # 1-D Array 
b = np.array([[10, 20, 30, 40],       # 2-D Array
              [90, 80, 70, 60]])
print(a)
print(b)
print(type(a))                        # Checking data type 
print(a.dtype)




# NumPy Silently Converts Mixed Types To One dtype -> 
c = np.array([1, 2, 3.5])                             # Turn everthing in FLOAT
d = np.array([1, 2, 3, "three"])                      # Turn everything in STRING
#e = np.array([[10, 20, 30],[40, 50, 60, 70]])        # ERROR {because rows is not equal to column(3 × 4)}
print(c)
print(d)
print(c.dtype)
print(d.dtype)
#print(e)


[1 2 3 4]
[[10 20 30 40]
 [90 80 70 60]]
<class 'numpy.ndarray'>
int64
[1.  2.  3.5]
['1' '2' '3' 'three']
float64
<U21


In [ ]:
# Array Generators : ones,zeros,full ->
f = np.zeros([3, 4])                     # 3x4 Matrix of 0(zero) 
g = np.ones(6)                           # 1d array of 6 1s
h = np.full((3,4),5)                     # 3x4 matrix filled with 5
print(f)
print(g)
print(h)
print()

# arange vs linspace->
i = np.arange(1,20,3)                     # START, STOP EXCLUDED, STEP
j = np.linspace(0,10,5)                   # Start, STOP INCLUDED, Number of values)
k = np.eye(4)                             # Creating 4x4 matrix, 1s on the diagonal, 0s elsewhere 
l = np.array([1, 2, 3, 4], dtype=float)   # It convert Integer into Float   

print(i)
print(j)
print()
print(k)
print(l)
print(m)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1.]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]



NameError: name 'arr' is not defined

NOTE: The output shows 0. with a decimal point because the default dtype of these generators is float64,
not int.

In [ ]:
# Array Attributes->
