In [ ]:
import numpy as np                # Import Numpy      

In [8]:
# Creating Array->
a = np.array([1, 2, 3, 4])            # 1-D Array 
b = np.array([[10, 20, 30, 40],       # 2-D Array
              [50,60,70,80]])
print(a)
print(b)
print(type(a))                        # Checking data type 



# NumPy Silently Converts Mixed Types To One dtype -> 
c = np.array([1, 2, 3.5])                             # Turn everthing in FLOAT
d = np.array([1, 2, 3, "three"])                      # Turn everything in STRING
#e = np.array([[10, 20, 30],[40, 50, 60, 70]])        # ERROR {because rows is not equal to column(3 × 4)}
print(c)
print(d)
#print(e)

[1 2 3 4]
[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>
[1.  2.  3.5]
['1' '2' '3' 'three']


In [12]:
# Array Generators : ones,zeros,full ->
f = np.zeros((2, 3) )                    # 2x3 Matrix of 0(zero) 
g = np.ones(5)                           # 1D array of 5 1s
h = np.full((3,3),7)                     # 3x3 matrix filled with 7
print(f)
print(g)
print(h)
print()

# arange vs linspace->
i = np.arange(1,15,2)                     # START, STOP EXCLUDED, STEP
j = np.linspace(0,15,1)
print(i)
print(j)

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[7 7 7]
 [7 7 7]
 [7 7 7]]

[ 1  3  5  7  9 11 13]
[0.]
