In [ ]:
# Creating Array->
import numpy as np
a = np.array([1, 2, 3, 4])            # 1-D Array 
b = np.array([[10, 20, 30, 40],       # 2-D Array
              [50,60,70,80]])
print(a)
print(b)


# NumPy Silently Converts Mixed Types To One dtype -> 
c = np.array([1, 2, 3.5])                               # Turn everthing in FLOAT
d = np.array([1, 2, 3, "three"])                        # Turn everything in STRING
#e = np.array([[10, 20, 30],[40, 50, 60, 70]])  
print(c)
print(d)
#print(e)

[1 2 3 4]
[[10 20 30 40]
 [50 60 70 80]]
[1.  2.  3.5]
['1' '2' '3' 'three']
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Array Generators : ones,zeros,full ->
f = np.zeros((2, 3))                     # 2x3 Matrix of 0(zero) 
g = np.ones(5)
print(f)
print(g)

SyntaxError: invalid syntax (3008379743.py, line 5)